media:
  path: src/lib/cms/media
  input: src/lib/cms/media
  # Actual value will be dynamically adjusted to either
  #   import($lib/cms/media/...) or enhanced:img(src="/src/lib/cms/media/...")
  # TODO: Consider using $lib here for easier identification of paths in code.
  output: /src/lib/cms/media
  categories: [image, document]
content:
  # TODO: Very repetitive - consider using slug routing and make this a list,
  #   similar to glog structure. Might need to automate menus.

  # About
  - name: about
    label: About
    type: file
    path: src/lib/cms/about.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Longevity
  - name: longevity
    label: Longevity
    type: file
    path: src/lib/cms/longevity.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Myobility
  - name: myobility
    label: Myobility
    type: file
    path: src/lib/cms/myobility.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # NLP and Hypnotherapy
  - name: nlp
    label: NLP and Hypnotherapy
    type: file
    path: src/lib/cms/nlp.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Pilates
  - name: pilates
    label: Pilates
    type: file
    path: src/lib/cms/pilates.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Personal Training
  - name: pt
    label: Personal Training
    type: file
    path: src/lib/cms/pt.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Transformation and Sobriety
  - name: transformation
    label: Transformation and Sobriety
    type: file
    path: src/lib/cms/transformation.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Yin
  - name: yin
    label: Yin
    type: file
    path: src/lib/cms/yin.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true

  # Yoga
  - name: yoga
    label: Yoga
    type: file
    path: src/lib/cms/yoga.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitles
        label: Subtitles
        type: string
        list: true
      - name: theme
        label: Theme
        description: For now, this just sets the divider image
        type: select
        options:
          values:
            - value: agua
              label: Agua
            - value: ocean
              label: Ocean
            - value: rockpool
              label: Rock Pool
            - value: spray
              label: Spray
            - value: storm
              label: Storm
      - name: body
        label: Body content
        type: rich-text
        required: true
