# You are viewing the Pages CMS settings file for the live site.
# It is empty because we don't want live edits.

# To update the preview site, open the menu on the left of this page,
# and select the "preview" branch.

# To view the preview site, go to https://preview.mickiyoga.pages.dev/
